spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/activity-managment-backend
    username: postgres
    password: 6819
    initialize: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect